### ISSUE TITLE
All Dependabot PRs Fail Initially

### ISSUE THREAD

**Issue by dkershner6** [alexromer0/pull-request-labeler#5]
```
Run alexromer0/pull-request-labeler@2.1.1
  with:
    GITHUB_TOKEN: ***
    xs_limit: 50
    sm_limit: 100
    md_limit: 300
    lg_limit: 600
/usr/bin/docker run --name a33c1f73cc93eb8dc42049dc1835285e291d9_97f0ac --label 8a33c1 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_XS_LIMIT -e INPUT_SM_LIMIT -e INPUT_MD_LIMIT -e INPUT_LG_LIMIT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/obfns-infrastructure-ops/obfns-infrastructure-ops":"/github/workspace" 8a33c1:f73cc93eb8dc42049dc1835285e291d9  "***" "50" "100" "300" "600"
[INFO] Github Event
/github/workflow/event.json
[INFO] Labelling pull request with size-xs
parse error: Invalid numeric literal at line 1, column 9
```

Re-running the same exact job succeeds.

Thanks for the action, btw!

**Comment by alexromer0** [comment]
Hi @dkershner6 
Thanks for the feedback... can you please provide your implementation file?

I tested it on one repo and it worked just fine, here my implementation:
```yml
name: Labeler

on: [pull_request]

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    name: 'Label the PR'
    steps:
      - name: Pull request size labelling
        uses: alexromer0/pull-request-labeler@2.1.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          xs_limit: '300'
          sm_limit: '600'
          md_limit: '900'
          lg_limit: '1200'
```

**Comment by dkershner6** [comment]
```yaml
name: Default PR Create Handling

on:
  pull_request:
    types:
      - opened

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Pull request size labelling
        uses: alexromer0/pull-request-labeler@2.1.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          xs_limit: '50'
          sm_limit: '100'
          md_limit: '300'
          lg_limit: '600'
```

Looks very similar...not sure why mine wouldn't work and yours would.  I have never had it fail on anything besides dependabot.
